services:
  db:
    image: postgres:16
    container_name: appservicos-db
    environment:
      POSTGRES_DB: appservicos
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  dbdata:
